// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Yukle.Api.Data;

#nullable disable

namespace Yukle.Api.Migrations;

[DbContext(typeof(YukleDbContext))]
[Migration("20260524120000_PhaseD2_AdminActionLogLoadPayment")]
partial class PhaseD2_AdminActionLogLoadPayment
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
