import { StyleSheet } from 'react-native';
import { Colors } from './colors';

export const adminScreenStyles = StyleSheet.create({
  scroll: { padding: 16, paddingBottom: 40, gap: 12 },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  backLink: { color: Colors.primary, fontSize: 15, marginBottom: 4 },
  title: { color: Colors.textPrimary, fontSize: 22, fontWeight: '700' },
  sub: { color: Colors.textSecondary, fontSize: 13, marginBottom: 4 },
  muted: { color: Colors.textSecondary, fontSize: 13 },
  mono: { color: Colors.textMuted, fontSize: 11, fontFamily: 'monospace' },
  card: {
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,107,0,0.25)',
    padding: 14,
    gap: 6,
  },
  cardTitle: { color: Colors.textPrimary, fontSize: 16, fontWeight: '700' },
  linkBtn: {
    backgroundColor: Colors.bgCard,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.primary,
    padding: 14,
    gap: 4,
  },
  linkTitle: { color: Colors.primary, fontSize: 16, fontWeight: '700' },
  linkSub: { color: Colors.textSecondary, fontSize: 12 },
  input: {
    backgroundColor: Colors.bgCard,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,182,39,0.3)',
    color: Colors.textPrimary,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  filterBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  filterBtnText: { color: '#050608', fontWeight: '700' },
  errorBox: {
    backgroundColor: 'rgba(239,68,68,0.12)',
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.35)',
  },
  errorText: { color: '#fca5a5', fontSize: 13 },
  successBox: {
    backgroundColor: 'rgba(34,197,94,0.1)',
    borderRadius: 8,
    padding: 10,
  },
  successText: { color: '#86efac', fontSize: 13 },
  empty: { padding: 24, alignItems: 'center' },
  emptyTitle: { color: Colors.textMuted, fontSize: 15 },
  placeholderBanner: {
    backgroundColor: 'rgba(255,182,39,0.1)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.primaryGold,
    padding: 12,
    gap: 4,
  },
  placeholderText: { color: Colors.primaryGold, fontSize: 13, lineHeight: 18 },
  danger: { color: '#f87171' },
  btnDanger: {
    backgroundColor: '#dc2626',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  btnDangerText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  btnDisabled: { opacity: 0.5 },
  statusOk: { color: '#4ade80' },
  statusBad: { color: '#f87171' },
});
